version: '3'

services:
  web-e-ramal:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-e-ramal
    #command: ["npm", "install" ,"npm", "start", "--", "--host", "0.0.0.0", "--poll", "500"]
    command: sh -c "npm install && npm start -- --host 0.0.0.0 --poll 500"
    ports:
      - "4200:4200"
    volumes:
      - ./:/app
